# Generated by Django 5.0.1 on 2024-02-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name: ')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname: ')),
                ('phone', models.CharField(max_length=200, verbose_name='Phone: ')),
                ('email', models.CharField(max_length=200, verbose_name='Email: ')),
                ('basket', models.TextField(verbose_name='Items: ')),
            ],
        ),
    ]
